In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/Indian_Kids_Screen_Time.csv")
df.head()

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,NaN,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban

Handle Missing Values

In [12]:
df["Health_Impacts"] = df["Health_Impacts"].fillna("None")

In [11]:
df.isnull().sum()

Age                                  0
Gender                               0
Avg_Daily_Screen_Time_hr             0
Primary_Device                       0
Exceeded_Recommended_Limit           0
Educational_to_Recreational_Ratio    0
Health_Impacts                       0
Urban_or_Rural                       0
dtype: int64

In [14]:
df["Gender"] = df["Gender"].str.strip()
df["Primary_Device"] = df["Primary_Device"].str.strip()
df["Urban_or_Rural"] = df["Urban_or_Rural"].str.strip()

Age Bands.

In [16]:
df["Age_Band"] = pd.cut(
    df["Age"],
    bins=[0,5,9,13,17],
    labels=["3-5","6-9","10-13","14-17"]
)

In [17]:
df[["Age","Age_Band"]].head()

   Age Age_Band
0   14    14-17
1   11    10-13
2   18      NaN
3   15    14-17
4   12    10-13

Screen Time Levels

In [18]:
df["Screen_Time_Level"] = pd.cut(
    df["Avg_Daily_Screen_Time_hr"],
    bins=[0,2,4,6,24],
    labels=["Low","Moderate","High","Very High"]
)

In [19]:
df[["Avg_Daily_Screen_Time_hr","Screen_Time_Level"]].head()

   Avg_Daily_Screen_Time_hr Screen_Time_Level
0                      3.99          Moderate
1                      4.61              High
2                      3.73          Moderate
3                      1.21               Low
4                      5.89              High

Save Clean Dataset for dashboard preparation

In [ ]:
df.to_csv("../data/processed/screensense_clean.csv", index=False)